#!/bin/sh
date_string="`date +"%Y-%m-%d %H:%M %Z"`"
for f in $( git diff --cached --name-only --diff-filter=ACM ); do
  # XXX broken: if space in filename(s)
  echo "Modifying version date of file" "$f" "$date_string"
  perl -pi -e 's{^; \$Id: .* \$}{; \$Id: '"$date_string"' \$};' $f
  git add -u -- "$f"
 done
 