#!/bin/sh
branch=`git rev-parse --abbrev-ref HEAD`
if [ "$branch" == "ssw-export" ]; then
  echo "On ssw-export branch, skipping version date update."
  exit 0
fi
date_string="$(date +"%Y-%m-%d %H:%M %Z")"
for f in $(git diff --cached --name-only --diff-filter=ACM); do
  # XXX broken: if space in filename(s)
  echo "Modifying version date of file" "$f" "$date_string"
  perl -pi -e 's{^; \$Id: .* \$}{; \$Id: '"$date_string"' \$};' $f
  git add -u -- "$f"
done
