# $Id:$
MODULE CFIT
DESCRIPTION DLM implementation of comp_poly.pro
VERSION $Revision: 1.0$
BUILD_DATE $Date: 2025/06/17 $
SOURCE S.V.H.HAUGAN
PROCEDURE COMP_POLY  3 4
PROCEDURE COMP_GAUSS  3 4
PROCEDURE CF_G_P0_ 3 4
PROCEDURE CF_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
PROCEDURE CF_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_G_P0_ 3 4
