include ../Makefile.$(SSW_COMPILE_TYPE)

CFLAGS		= -c -I$(IDL_DIR)/external/include
FFLAGS          = -c

# Shorthand
.SUFFIXES: .$(SO_EXT) .c .o

clean : 
	rm -f *.o *.$(SO_EXT) so_locations

neat : clean
	rm -f *~ \#*

.c.o:
	$(CC) $(CFLAGS) $(X_CFLAGS) $*.c

.o.$(SO_EXT): 
	$(LD) $(X_LD_FLAGS) -o $@ $?
